Traceback (most recent call last):
  File "traceback_demo.py", line 4, in <module>
    raise Exception("This is the error message :)")
Exception: This is the error message :)
